language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
after_success:
  - julia -e 'cd(Pkg.dir("DistributedArrays")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
